spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/consul_plan
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testfist24@gmail.com
    password: xyoj cvkf evum nhmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  config:
    allowed-origin-patterns: "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    permit-all-endpoints:
      - "/auth/**"
      - "/admin/**"
      - "/api/**"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
    authenticated-endpoints:
      - "/**"
reminder:
  scheduler:
    enabled: true
    cron: "0 0 12 * * ?"
logging:
  file:
    name: logs/app.log
  level:
    org.springframework.web: DEBUG
    ru.promo.consul_plan: DEBUG
token:
  signing:
    key: "PromoIt"
server:
  port: 8080