spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/consul_plan
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

feign:
  client:
    config:
      notification-service:
        url: http://localhost:8181

retry:
  scheduler:
    enabled: true
    cron: "0 */10 * * * ?"

kafka:
  consultation-topic: "consultation-topic"


security:
  config:
    allowed-origin-patterns: "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    permit-all-endpoints:
      - "/auth/**"
      - "/admin/**"
      - "/api/**"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
    authenticated-endpoints:
      - "/**"
logging:
  file:
    name: logs/app.log
  level:
    org.springframework.web: DEBUG
    ru.promo.consul_plan: DEBUG
token:
  signing:
    key: "PromoIt"
server:
  port: 8080